version: '3.8'
services:
  playwright:
    build: 
      context: ./
    volumes:
        - ../e2e:/var/scenario
    container_name: playwright
    # 起動時に対象のシナリオを実行する
    entrypoint: >
      sh -c "
        cd /var/scenario &&
        python 
      "